[tool.poetry]
name = "repl_python3_Lab04"
version = "0.1.0"
description = ""
authors = ["QuintinForsyth1 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
shapes = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
